load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(default_visibility = ["//:__subpackages__"])

cc_library(
    name = "weight_managers",
    hdrs = ["weight_managers.hpp"],
    deps = ["//tiny_llm/common:common_macros"],
)
