"""
"""
module(
    name = "tiny_llm",
    version = "0.0.0",
)

bazel_dep(name = "rules_cc", version = "0.2.17")

bazel_dep(name = "googletest", version = "1.17.0.bcr.1")

bazel_dep(name = "spdlog", version = "1.16.0")

bazel_dep(name = "rules_cuda", version = "0.3.0")
cuda = use_extension("@rules_cuda//cuda:extensions.bzl", "toolchain")
cuda.toolkit(
    name = "cuda",
    toolkit_path = "",
)
use_repo(cuda, "cuda")

bazel_dep(name = "platforms", version = "1.0.0")

host_platform = use_extension("//:tools/gen_platforms.bzl", "host_platform")
use_repo(host_platform, "host_platform")

bazel_dep(name = "rules_rust", version = "0.68.1")
crate = use_extension("@rules_rust//crate_universe:extensions.bzl", "crate")
crate.from_cargo(
    name = "safetensors_deps",
    cargo_lockfile = "//tiny_llm/weight_managers/safetensors:Cargo.lock",
    lockfile = "//tiny_llm/weight_managers/safetensors:Cargo.Bazel.lock",
    manifests = ["//tiny_llm/weight_managers/safetensors:Cargo.toml"],
)
use_repo(crate, "safetensors_deps")
crate.from_cargo(
    name = "tokenizers_deps",
    cargo_lockfile = "//tiny_llm/tokenizers/huggingface:Cargo.lock",
    lockfile = "//tiny_llm/tokenizers/huggingface:Cargo.Bazel.lock",
    manifests = ["//tiny_llm/tokenizers/huggingface:Cargo.toml"],
)
use_repo(crate, "tokenizers_deps")

bazel_dep(name = "google_benchmark", version = "1.9.5")

bazel_dep(name = "nlohmann_json", version = "3.12.0.bcr.1")

bazel_dep(name = "gflags", version = "2.2.2.bcr.1")
