load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(default_visibility = ["//:__subpackages__"])

cc_library(
    name = "thread_pool",
    hdrs = ["thread_pool.hpp"],
    deps = ["//tiny_llm/common:log_and_excepts"],
)
