package(default_visibility = ["//tests:__subpackages__"])

filegroup(
    name = "datas",
    srcs = [
        "apply_rope_s2_d96.safetensors",
        "attn_res_b2q107h4k123h2d61.safetensors",
        "casual_attn_res_b2l107q4k2d61.safetensors",
        "gemm_m127d255n353.safetensors",
        "rope_s2_d96.safetensors",
        "test.safetensors",
    ],
)
