package(default_visibility = ["//tests:__subpackages__"])

filegroup(
    name = "datas",
    srcs = [
        "apply_rope_s2_d96.safetensors",
        "attn_res_b2q107h4k123h2d61.safetensors",
        "bert_base_uncased_tokenizer.json",
        "causal_attn_res_b2l107q4k2d61.safetensors",
        "gemm_b2h4q127d61od313.safetensors",
        "gemm_b2q61d255oh4od88qs3qe77.safetensors",
        "gemm_m127d255n353.safetensors",
        "rms_norm_b2l107d241.safetensors",
        "rope_s2_d96.safetensors",
        "test.safetensors",
    ],
)
